import type { AuditReport, FormatOptions, Severity, Vulnerability } from '../types.js';
import { filterBySeverity } from '../threshold.js';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'moderate', 'low', 'info'];

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  moderate: '🟡',
  low: '🔵',
  info: '⚪',
};

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: 'Critical',
  high: 'High',
  moderate: 'Moderate',
  low: 'Low',
  info: 'Info',
};

function countBySeverity(vulns: Vulnerability[]): Record<Severity, { count: number; fixable: number }> {
  const result: Record<Severity, { count: number; fixable: number }> = {
    critical: { count: 0, fixable: 0 },
    high: { count: 0, fixable: 0 },
    moderate: { count: 0, fixable: 0 },
    low: { count: 0, fixable: 0 },
    info: { count: 0, fixable: 0 },
  };
  for (const v of vulns) {
    result[v.severity].count += 1;
    if (v.fixAvailable) result[v.severity].fixable += 1;
  }
  return result;
}

function renderVulnerability(v: Vulnerability): string {
  const lines: string[] = [];
  lines.push(`### ${v.name}`);
  lines.push(`- **ID:** ${v.id}`);
  lines.push(`- **Title:** ${v.title}`);
  lines.push(`- **Range:** \`${v.range}\``);
  if (v.fixAvailable && v.fixCommand) {
    lines.push(`- **Fix:** \`${v.fixCommand}\``);
  } else {
    lines.push(`- **Fix:** No fix available`);
  }
  if (v.url) lines.push(`- **Advisory:** ${v.url}`);
  if (v.paths.length > 0) lines.push(`- **Paths:** \`${v.paths.join(', ')}\``);
  return lines.join('\n');
}

export function markdown(report: AuditReport, opts: FormatOptions = {}): string {
  const title = opts.title ?? 'npm audit report';
  const minSeverity = opts.severity ?? 'info';
  const filtered = filterBySeverity(report.vulnerabilities, minSeverity);

  const out: string[] = [];
  out.push(`## ${title}`);
  out.push('');

  if (filtered.length === 0) {
    out.push(`## ✅ No vulnerabilities found`);
    out.push('');
    const date = report.meta.auditedAt ? report.meta.auditedAt.slice(0, 10) : '';
    out.push(
      `> 0 vulnerabilities found · audited ${date} · ${report.meta.totalDependencies} dependencies`,
    );
    out.push('');
    out.push(`---`);
    out.push(`*Generated by [audit-report](https://github.com/dimasdarfi/audit-report)*`);
    return out.join('\n');
  }

  const date = report.meta.auditedAt ? report.meta.auditedAt.slice(0, 10) : '';
  out.push(
    `> ${filtered.length} vulnerabilities found · audited ${date} · ${report.meta.totalDependencies} dependencies`,
  );
  out.push('');

  const counts = countBySeverity(filtered);

  out.push(`| Severity | Count | Fixable |`);
  out.push(`|----------|-------|---------|`);
  for (const sev of SEVERITY_ORDER) {
    const c = counts[sev];
    if (c.count === 0) continue;
    out.push(`| ${SEVERITY_EMOJI[sev]} ${SEVERITY_LABEL[sev]} | ${c.count} | ${c.fixable} |`);
  }
  out.push('');
  out.push('---');
  out.push('');

  for (const sev of SEVERITY_ORDER) {
    const group = filtered.filter((v) => v.severity === sev);
    if (group.length === 0) continue;
    out.push(`<details>`);
    out.push(`<summary>${SEVERITY_EMOJI[sev]} ${SEVERITY_LABEL[sev]} (${group.length})</summary>`);
    out.push('');
    for (const v of group) {
      out.push(renderVulnerability(v));
      out.push('');
    }
    out.push(`</details>`);
    out.push('');
  }

  out.push('---');
  out.push(`*Generated by [audit-report](https://github.com/dimasdarfi/audit-report)*`);
  return out.join('\n');
}
